### ISSUE TITLE
Add no_std feature?

### ISSUE THREAD

**Issue by Kijewski** [rinja-rs/rinja#15]
I think the generated code can easily be `#![no_std]`. We only _need_ `std` to `impl std::error::Error for rinja::Error`. We _need_ `alloc` for a few filters. Both use cases can be feature-gated. Then I think, we can add the features ↓ and be useful to a marginally wider audience.

```toml
default = […, "std"]
std = ["alloc"]
alloc = []
```

What do you think?
